applicationName: accounting-service
server:
  type: simple
  applicationContextPath: /api
  adminContextPath: /admin/accounting
  connector:
    type: http
    port: 8083
circuitBreaker:
  rateType: MEAN
  threshold: 2.0