applicationName: order-service
server:
  type: simple
  applicationContextPath: /api
  adminContextPath: /admin/order
  connector:
    type: http
    port: 8080
circuitBreaker:
  rateType: MEAN
  threshold: 2.0
